version: "3"
services:

  redis:
    image: redis
    ports:
      - "6379"
    network_mode: "host"
    volumes:
      - redis-data:/data

  db:
    image: postgres
    environment:
      POSTGRES_USER: dotnetUser
    restart: on-failure # "no" | always | on-failure | unless-stopped   
    ports:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    network_mode: "host"

  angularapp:
    build: ./AngularApplication
    ports:
      - "4200"
    network_mode: "host"
    depends_on:
      - authservice
      - fileservice  

  authservice:
    build:
      context: .
      dockerfile: ./AuthenticationService/Dockerfile
    ports:
      - "5000"
    network_mode: "host"
    depends_on:
      - redis
      - db

  fileservice:
    build:
      context: .
      dockerfile: ./FileService/Dockerfile
    ports:
      - "5001"
    network_mode: "host"
    volumes:
        - fileservice-data:/app/Content
    depends_on:
      - redis
      - db
          
volumes:
  db-data:
  redis-data:
  fileservice-data: