version: "3"
services:

  redis:
    image: redis
    ports:
      - "6379"
    network_mode: "host"
    volumes:
      - redis-data:/data

  db:
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: AdminPassword1
    restart: on-failure # "no" | always | on-failure | unless-stopped   
    ports:
      - "1433"
    volumes:
      - db-data:/var/opt/mssql
    network_mode: "host"

  angularapp:
    build: ./AngularApplication
    environment:
      ASPNETCORE_URLS: "http://*:4200"
    ports:
      - "4200"
    network_mode: "host"
    depends_on:
      - authservice
      - fileservice  

  authservice:
    build:
      context: .
      dockerfile: ./AuthenticationService/Dockerfile
    environment:
      ASPNETCORE_URLS: "http://*:5000"
    ports:
      - "5000"
    network_mode: "host"
    depends_on:
      - redis
      - db

  fileservice:
    build:
      context: .
      dockerfile: ./FileService/Dockerfile
    environment:
      ASPNETCORE_URLS: "http://*:5001"
    ports:
      - "5001"
    network_mode: "host"
    volumes:
        - fileservice-data:/app/Content
    depends_on:
      - redis
      - db
      
  init-db:
    build: ./DockerUtils
    network_mode: "host"
    depends_on:
      - redis
      - db
            
volumes:
  db-data:
  redis-data:
  fileservice-data: